const myList = [["TCPMUX",1],
["ECHO PROTOCOL",7],
["DISCARD PROTOCOL",9],
["DAYTIME PROTOCOL",13],
["QUOTE OF THE DAY",17],
["MESSAGE SEND PROTOCOL",18],
["CHARACTER GENERATOR PROTOCOL",19],
["FILE TRANSFER PROTOCOL DATA",20],
["FILE TRANSFER PROTOCOL CONTROL",21],
["SECURE SHELL",22],
["TELNET",23],
["SIMPLE MAIL TRANSFER PROTOCOL",25],
["NSW-FE NSW USER SYSTEM FE",27],
["MSG ICP",29],
["MSG AUTHENTICATION",31],
["DISPLAY SUPPORT PROTOCOL",33],
["TIME PROTOCOL",37],
["ROUTE ACCESS PROTOCOL",38],
["RESOURCE LOCATION PROTOCOL",38],
["GRAPHICS",41],
["HOSTNAME SERVER PROTOCOL",42],
["WHO IS PROTOCOL",43],
["TACACS LOGIN HOST PROTOCOL",49],
["DOMAIN NAME SYSTEM",53],
["WHOIS++",63],
["DHCP",67],
["DHCP",68],
["TRIVIAL FILE TRANSFER PROTOCOL",69],
["HYPER TEXT TRANSFER PROTOCOL",80],
["POST OFFICE PROTOCOL VERSION2",109],
["POST OFFICE PROTOCOL VERSION3",110],
["SIMPLE FILE TRANSFER PROTOCOL",115],
["SQL SERVICES",118],
["NETWORK NEWS TRANSFER PROTOCOL",119],
["NETWORK TIME PROTOCOL",123],
["INTERNET MESSAGE ACCESS PROTOCOL",143],
["SIMPLE GATEWAY MONITORING PROTOCOL",153],
["SIMPLE NETWORK MANAGEMENT PROTOCOL",161],
["SIMPLE NETWORK MANAGEMENT PROTOCOL TRAP",161],
["BORDER GATEWAY PROTOCOL",179],
["LIGHT WEIGHT DIRECTORY ACCESS PROTOCOL",389],
["HYPERTEXT TRANSFER PROTOCOL SECURE",443],
["SIMPLE NETWORK PAGING PROTOCOL",444],
["ROUTING INFORMATION PROTOCOL",520],
["REMOTE SHELL",514],
["SYSLOG",514],
["REMOTE PROCEDURE CALL ",530],
["DHCPV6 CLIENT",546],
["DHCPV6 SERVER",547],
["REALTIME STREAMING PROTOCOL",554]
];

console.log(myList);
console.log("portnumber of",myList[0][0],"is:",myList[0][1]);
console.log(myList.length);
console.log("portnumber of",myList[49][0],"is",myList[49][1]);
console.log("portnumber of",myList[48][0],"is",myList[48][1]);
console.log("portnumber of",myList[45][0],"is",myList[45][1]);
console.log("portnumber of",myList[30][0],"is",myList[30][1]);
console.log("portnumber of",myList[11][0],"is",myList[11][1]);
console.log("portnumber of",myList[12][0],"is",myList[12][1]);
console.log("portnumber of",myList[13][0],"is",myList[13][1]);
console.log("portnumber of",myList[16][0],"is",myList[16][1]);












